spring.application.name=server

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

logging.level.liquibase=DEBUG
debug=true

#spring.data.redis.host=${REDIS_HOST:localhost}
#spring.data.redis.port=${REDIS_PORT:6379}
#spring.data.redis.ssl.enabled=${REDIS_SSL:false}
spring.data.redis.cluster.nodes=${REDIS_CLUSTER_NODES}
spring.data.redis.ssl.enabled=true
spring.data.redis.maxmemory-policy=allkeys-lru