spring.application.name=server

spring.datasource.url=jdbc:postgresql://localhost:5432/pocketlibrary
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
#spring.datasource.password= abc
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

logging.level.liquibase=DEBUG
debug=true

spring.redis.host=localhost
spring.redis.port=6379
spring.redis.maxmemory-policy=allkeys-lru