springdotenv.enabled=false
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.ssl.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5432/pocketlibrary
spring.datasource.username=postgres
spring.datasource.password=localdev